### ISSUE TITLE
Request: tag a version

### ISSUE THREAD

**Issue by mcandre** [molecula/noticeme#2]
Hi,

As a DevOp, I would like noticeme to publish at least one version number like "v0.0.1", so that I can pin my dependencies to a specific version. Version numbers help to mitigate any future API breakages that could cause havoc in a large CI/CD pipeline.

Without a git tag, then I would have to resort to using something like a raw git commit ID, which creates additional maintenance problems.

**Comment by seebs** [comment]
that seems reasonable, have attempted to push a tag of v0.1 including the most recent change
