### ISSUE TITLE
internal error

### ISSUE THREAD

**Issue by mcandre** [molecula/noticeme#3]
When I try to analyze my Go project with noticeme, then I get an internal error.

Trace:

```console
$ git clone https://github.com/mcandre/buttery.git
$ cd buttery
$ noticeme .
noticeme: internal error: package "image" without types was imported from "github.com/mcandre/buttery"
```

However, my project builds fine with standard Go tooling. And it lints fine with other linters.

Perhaps noticeme isn't integrating with the go mod system when resolving imports?

**Comment by seebs** [comment]
Huh. That seems pretty possible, I'm guessing the import golang.org/x/tools is several years out of date. probably just updating it will work. I'll see if I can get that updated (and also do the version tag you suggested).

**Comment by seebs** [comment]
should be fixed now. thanks for the report!
